wip: SCOR-143 cleanup errors complained of by amplify frontend hosting
other than error TS1205: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.